### ISSUE TITLE
4:3 aspect ratio is broken on ScreenMusicSelect

### ISSUE THREAD

**Issue by FishamanP** [CrashCringle12/Simply-Love-SM5#14]
As the title says, should be fairly obvious just from testing. Sorry for no screenshots right now, I don't have much spare time.

**Comment by CrashCringle12** [comment]
Ah yeah. All good, thanks for letting me know.

**Comment by CrashCringle12** [comment]
This PR (https://github.com/CrashCringle12/Simply-Love-SM5/pull/15) from @quietly-turning fixes the issue as long as Groovestats are not enabled. Working to get a commit out to fix the screen while Groovestats is enabled.

**Comment by quietly-turning** [comment]
> as long as Groovestats are not enabled

whoops
